Solve compilation error in benchmarks due to Map.fromSet.
The benchmarks suite fails to compile with

    benchmarks/Benchmarks.hs:361:29:
        Not in scope: `Map.fromSet'
        Perhaps you meant one of these:
          `Map.fromList' (imported from Data.Map),
          `C.fromSet' (imported from Data.CritBit.Map.Lazy)

This is because function `fromSet` is in `Data.Map.Lazy`, not in `Data.Map`.
This patch adds the needed `import` line and modifies the `critbit.cabal` file
to place a lower-bound on `containers` package (`Data.Map.Lazy` exists since
`containers-0.5.0.0`.