Solve compilation error in benchmarks due to Map.fromSet.
The benchmarks suite fails to compile with

    benchmarks/Benchmarks.hs:361:29:
        Not in scope: `Map.fromSet'
        Perhaps you meant one of these:
          `Map.fromList' (imported from Data.Map),
          `C.fromSet' (imported from Data.CritBit.Map.Lazy)

Function `fromSet` was added in `containers-0.5.0.0` (via `Data.Map.Lazy`
module). This patch moves the benchmark lines inside the proper corresponding
preprocessor directives.